version: '3'
services:
  pokemon-api:
    build: ./pokemon-api
    container_name: pokemon-api
    environment:
      - ConnectionStrings__PokemonDatabaseConnectionString=User ID=admin;Password=admin;Host=pokemon-db;Port=5432;Database=Pokemons;
      - PokemonImageApiBaseUrl=http://pokemon-image-api:3000
    ports:
      - "5000:80"
    networks:
      - "pokemon-network"
  pokemon-image-api:
    build: ./pokemon-image-api
    container_name: pokemon-image-api
    ports:
      - "3000:3000"
    networks:
      - "pokemon-network"
  pokemon-db:
    image: postgres
    container_name: pokemon-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=Pokemons
      - POSTGRES_PASSWORD=admin
    volumes:
      - /Users/aleifsson/src/ru/WebServicesRU/docker/dotnet/pokemon-stack/init-scripts:/docker-entrypoint-initdb.d/
    networks:
      - "pokemon-network"
networks:
  pokemon-network:
    driver: bridge
